backend:
  name: git-gateway
  branch: main

# This line enables the local backend proxy for development
local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    post_create_redirect: "/#blog"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}